apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "maskeyawash@gmail.com #enter your email to get the id
  GMAIL_PASSWORD: "ykxk ucif rhbx erjy"
type: Opaque

# Passw0rd@1234
